fragment ListingRow on Listing {
  id
  title
  image
  condition
  stock
  price
  shippingPrice
  purchaseOptions
  location
  listingAt
  listingEndAt
  returns
  buyItNowPrice
  currency
  bidsCount
  sellerId
  seller {
    id
    username
    totalFeedback
    feedbackText
  }
}
