#import "~/queries/fragments/ListingRow.gql"
#import "~/queries/fragments/Paging.gql"

query ListingsPage {
  listings(
    paging: { pageSize: 240 }
    orderBy: [{ field: "title", direction: DESC }]
  ) {
    entities {
      ...ListingRow
    }
    paging {
      ...Paging
    }
  }
}
