#import "~/queries/fragments/WarehouseReceiveRow.gql"
#import "~/queries/fragments/Paging.gql"

query WarehouseReceivesPage(
  $filter: WarehouseReceiveFilterInput
  $orderBy: [OrderByInput!]
) {
  warehouseReceives(
    filter: $filter
    paging: { pageSize: 240 }
    orderBy: $orderBy
  ) {
    entities {
      ...WarehouseReceiveRow
    }
    paging {
      ...Paging
    }
  }
}
